baseurl = "https://replace-this-with-your-domain.com/"
languageCode = "es-es"
title = "Type Moon theme"
theme = "hugo-type-moon-theme"

#  Activar comentarios Disqus
disqusShortname = "spf13"

# Activar Google Analytics
googleAnalytics = ""

# Posts por pagina
paginate = 10

# Comenta la opción themesDir si usa este tema en producción
# themesDir = "../.."


[params]
	author = "Your name"
	description = "Add a description of your website"

	# Las palabras clave se agregarán como una metaetiqueta. Delimítelos con una coma.
	keywords = "keyA,keyB,KeyC..."

	# Custom Avatar
	# ruta del avatar
	avatar = "img/avatar.png"

	# o usa gravatar con la dirección email
	gravatar = "your@email.com"

	headerText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br><br>Remove all header text in **config.toml** to disable this feature."

	# Para agregar un fondo de encabezado al sitio principal, 
	# guarde su imagen en static/img/imagen.png
	# y asigna "imagen.png"a la variable headerImage. Si no se proporciona una ruta de imagen,
	# en su lugar, se mostrará un fondo naranja.
	headerImage = ""
	copyright = "Released under the MIT license<br>Powered by [Hugo](https://gohugo.io/) with the [Type Moon Theme](https://github.com/moonantonio/hugo-type-moon-theme)"

	# Establecer título para la plantilla opengraph de Hugo
	title = "Type Moon theme"
	
	[taxonomies]
		# Utiliza la taxonomía de series para agrupar publicaciones de blog en series. 
		# Artículos relacionados de la serie será utilizado por la plantilla opengraph de Hugo.
  		series = "series"
		tags = "tags"
		categories = "categories"

	# Defina qué tipos de contenido se mostrarán en la página de inicio. Por defecto Hugo usa
	# tipos con más archivos de contenido.
	# mainSections = []

	[params.social]
		# Insertar los nombres
		public = ""
		about = ""
		separator = true
		rss = true
		homepage = true
		email = ""
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "MoonAntonio"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
		gitlab = ""
		trello = ""
		meetup = ""
		speackerdeck = ""