baseurl: "https://replace-this-with-your-domain.com/"
languageCode: "es-es"
title: "Type Moon Theme"
theme: "hugo-type-moon-theme"

# Activar Google Analytics
googleAnalytics: "UA-64342623-1"
privacy:
  googleAnalytics:
    anonymizeIP: true

# Activar comentarios Disqus
disqusShortname: "spf13"

# Posts por pagina
paginate: 10
permalinks:
  post: /blog/:title/

SectionPagesMenu: "nav"
# themesDir: "../.."

# Resaltado de sintaxis
pygmentsCodeFences: true
pygmentsStyle: "friendly"

# Característica de contenido relacionado
related:
  threshold: 100
  includeNewer: true
  toLower: true
  indices:
    - name: keywords
      weight: 10
    - name: tags
      weight: 100

params:
  mainSections:
    - "post"
  author: "Your name"
  description: "Add a description of your website"
  keywords: "keyA,keyB,keyC..."
  copyright: "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Moon Theme](//github.com/moonantonio/hugo-type-moon-theme)"
  headerText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br><br>Remove all header text in **config.yaml** to disable this feature."
  headerImage: "bg.png"
  avatar: "img/avatar.png"
  gravatar: ""

  logo:
    logoText: "hello friend"
    logoHomeLink: "/"
      # or
      #
      # path = "/img/your-example-logo.svg"
      # alt = "Your example logo alt text"

  social:
    devblog: "tags/devblog/"
    backdoor: "backdoor"
    public: "moonantonio/rec.repos"
    about: "portfolio/"
    separador: true
    rss: true
    email: "youemail@gmail.com"
    behance: ""
    bitbucket: ""
    dribbble: ""
    facebook: ""
    flickr: ""
    googleplus: ""
    instagram: ""
    linkedin: ""
    pinterest: ""
    reddit: ""
    soundcloud: ""
    stackexchange: ""
    steam: ""
    tumblr: ""
    twitter: ""
    wordpress: ""
    youtube: ""
    github: "moonantonio"
    trello: "moonantonio"
    gitlab: "moonantonio"
    meetup: ""
    speakerdeck: ""
