# Ajustes Obligatorios
baseurl = "http://replace-this-with-your-domain.com/"
languageCode = "en-us"
title = "Type moon theme"
theme = "hugo-type-moon-theme"

# Plugins
# Activar comentarios Disqus
disqusShortname = "spf13"
# Activar Google Analytics
googleAnalytics = ""

# Ajustes Generales
# Posts por pagina
paginate = 10
# Comenta themesDir si estas en produccion
# Esto solo es para montar server desde exampleSite
#themesDir = "../.."

[params]
	author = "Your name"
	description = "Add a description of your website"
	# Los keywords del meta. Delimitado por comas.
	keywords = ""
	# Custom Avatar
	# ruta del avatar
	avatar = "img/avatar.png"
	# o usa gravtar con la direccion email
	gravatar = ""
	headerText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br><br>Remove all header text in **config.toml** to disable this feature."
	headerImage = "bg.png"
	copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Moon Theme](//github.com/moonantonio/hugo-type-moon-theme)"

	[params.social]
		# Insertar los nombres de cuenta
        devblog = "devblog/"
		backdoor = "backdoor"
		public = "MoonAntonio/rec.repos"
		about = "portfolio/"
		separador = true
		rss = true
		homepage = true
		email = "hello@example.com"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "moonantonio/"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
		gitlab = ""
		trello = ""
